services:
  - type: web
    name: chatterbox-ajithranka-com
    env: static
    branch: main
    buildCommand: npm run generate
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /
